### ISSUE TITLE
Candidates don't have tracknumbers

### ISSUE THREAD

**Issue by JOJ0** [Samik081/beets-beatport4#1]
Hi,
thanks for maintaining a solution while the official beatport plugin is gone! I just came across some older Techno tracks that I'd like to import and they are nowhere to be found on Discogs or MusicBrainz. Just Beatport ;-) So: Thanks a ton!

I realised that tracknumbers are always missing in the candidates. I didn't investigate what to the problem could be, just reporting for now:

```
(Similarity: 42.5%) (missing tracks, media, source, tracks) (Beatport, Digital, 2009, Plus 8 Records, PLUS8100B)
 * Theychx (Tobias. Fuse Remix) (#12) (10:53) -> Intro (From Our Minds To Yours) (Tiefschwarz Remix) (#None) (10:40) (title, source, length)
Missing tracks (9/10 - 90.0%):
 ! 5 (Alex Under Remix)             (#None) (6:57)
 ! Ethnik (Paco Osuna Remix)        (#None) (9:45)
 ! Goo (Paco Osuna Remix)           (#None) (8:28)
 ! Hardphunk (Mike Shannon Reshake) (#None) (8:27)
 ! Kriket (Danilo Vigorito Remix)   (#None) (5:58)
 ! Statikphunk (Ambivalent Remix)   (#None) (6:04)
 ! Substance Abuse (Barem Remix)    (#None) (8:17)
 ! Vortex (Function Remix)          (#None) (7:18)
 ! Vortex (Hobo's Vile Remix)       (#None) (5:49)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, plaY, eDit, edit Candidates? 

```

Hope that helps and thanks again!

**Comment by JOJ0** [comment]
Also I just realise right now that not all tracks containend on this release are listed as the missing tracks. That's a second issue I guess: https://beatport.com/release/the-remixes/2292897

**Comment by Samik081** [comment]
Thank you, @JOJ0, for the kind words and reporting those issues with the examples! I'll have a look this week :)

**Comment by JOJ0** [comment]
Hi, thanks for taking a look and sorry for the late delay!

Ok, so now what I've tried so far:

- Checking out from current beets master (had quite some unmerged features in use)
- Disabling ALL plugins except beatport4

It's happening still.

Also I found out that it happens with single files as well. This is an example import command.

```
$ beet import -t /remote/data/music-archive/0-andi/Februar\ 2011/Alexander\ Ross\ -\ 01\ -\ Room.mp3

/remote/data/music-archive/0-andi/Februar 2011/Alexander Ross - 01 - Room.mp3 (1 items)
Correcting tags from:
    Alexander Ross - Universal Consciousness 1.1
To:
    Argy, Alexander Ross - Universal Consciousness 1.1
URL:
    https://beatport.com/release/universal-consciousness-11/217494
(Similarity: 78.1%) (media, missing tracks, artist, source, tracks) (Beatport, Digital, 2010, These Days, TD05)
 * Room (#1) -> Room (#None) (source)
Missing tracks (1/2 - 50.0%):
 ! Sometimes I'm Blind (#None) (6:31)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? 

````


I include the beatport plugin config from an extra yaml file, if that matters:

```
beatport4:
    source_weight: 0.2
    username: <secret>
    password: <secret>
    tokenfile: beatport_token.json
    client_id:
```

**Comment by JOJ0** [comment]
Some more config parts that might be of interest:

```
match:
    ignored_media:
    - Data CD
    - DVD
    - DVD-Video
    - Blu-ray
    - HD-DVD
    - VCD
    - SVCD
    - UMD
    - VHS
    strong_rec_thresh: 0.15
    medium_rec_thresh: 0.65
    max_rec:
        missing_tracks: strong
        unmatched_tracks: medium
    distance_weights:
        track_title: 1.5
        album: 4.0
        catalognum: 2.0
        track_id: 2.5
    preferred:
        media:
        - Vinyl
        - 12"
        - 2x12"
        - LP
        - CD
        - Digital Media|File
        - Cassette
        countries: [GB, DE, FR]
        original_year: no

```


```
import:
    log: remotebeets-import.log
    copy: yes
    move: no
    write: yes
    resume: ask
    from_scratch: yes
    default_action: apply
    detail: yes
    non_rec_action: ask
    duplicate_action: merge
    incremental_skip_later: no
    incremental: yes
    group_albums: no
    bell: yes
    autotag: yes
    autotag_exclude_fields: []
    duplicate_keys:
        album: albumartist album catalognum
        item: artist title catalognum
    set_fields:
        genre_orig_dir: Andi2011
    ```
